project:
  type: book

book:
  title: "linkdatagen-manual"
  author:
    - Melanie Bahlo
    - Catherine Bromhead
    - Tom Scerri
    - Katherine Smith
    - Rick Tankard
    - Luke Gandolfo
  date: "5 Sep 2022"
  lang: en-GB
  chapters:
    - index.qmd
    - download.qmd

    - part: Getting started'
      chapters:
      - snp-chip-quick-start.qmd
      - mps-quick-start.qmd
      - command-line-options.qmd

    - part: General notes
      chapters:
      - further-comments.qmd
      - general-comments.qmd
      - marker-frequency.qmd
      - test-datasets.qmd

    - part: Postface
      chapters:
      - help.qmd
      - acknowledgments.qmd
      - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt
  docx:
    default

editor: visual

execute:
  freeze: auto
