project:
  type: book

book:
  title: "LINKDATAGEN Manual"
  author:
    - Melanie Bahlo
    - Catherine Bromhead
    - Tom Scerri
    - Katherine Smith
    - Rick Tankard
    - Luke Gandolfo
  date: last-modified
  lang: en-GB

  reader-mode: true
  site-url: https://linkdatagen.netlify.app
  repo-url: https://github.com/bahlolab/linkdatagen-manual
  repo-actions: [edit, issue]

  chapters:
    - index.qmd

    - part: Getting started
      chapters:
      - download.qmd
      - snp-chip-quick-start.qmd
      - mps-quick-start.qmd

    - part: linkdatagen.pl
      chapters:
      - command-line-options.qmd
      - cheat-sheet.qmd

    - part: VCF and PLINK files
      chapters:
      - vcf2linkdatagen.qmd
      - plink_format_input.qmd

    - part: General notes
      chapters:
      - further-comments.qmd
      - general-comments.qmd
      - marker-frequency.qmd
      - test-datasets.qmd

    - part: Postface
      chapters:
      - help.qmd
      - acknowledgments.qmd
      - references.qmd

bibliography: references.bib

number-sections: true

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt
  docx:
    default

editor: visual

execute:
  freeze: auto
