project:
  type: book

book:
  title: "linkdatagen-manual"
  author:
    - Melanie Bahlo
    - Catherine Bromhead
    - Tom Scerri
    - Katherine Smith
    - Rick Tankard
    - Luke Gandolfo
  date: "5 Sep 2022"
  lang: en-GB
  chapters:
    - index.qmd
    - download.qmd
    - usage.qmd
    - further-comments.qmd
    - general-comments.qmd
    - marker-frequency.qmd
    - test-datasets.qmd
    - help-acknowledgments.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt
  docx:
    default

editor: visual

execute:
  freeze: auto
