project:
  type: book

book:
  title: "LINKDATAGEN Manual"
  author:
    - Melanie Bahlo
    - Catherine Bromhead
    - Tom Scerri
    - Katherine Smith
    - Rick Tankard
    - Luke Gandolfo
  date: last-modified
  lang: en-GB

  reader-mode: true
  site-url: https://linkdatagen.netlify.app
  repo-url: https://github.com/bahlolab/linkdatagen-manual
  repo-actions: [edit, issue]

  chapters:
    - index.qmd
    - download.qmd

    - part: Getting started
      chapters:
      - snp-chip-quick-start.qmd
      - mps-quick-start.qmd
      - command-line-options.qmd

    - part: General notes
      chapters:
      - further-comments.qmd
      - general-comments.qmd
      - marker-frequency.qmd
      - test-datasets.qmd

    - part: Postface
      chapters:
      - help.qmd
      - acknowledgments.qmd
      - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt
  docx:
    default

editor: visual

execute:
  freeze: auto
