on:
  workflow_dispatch:
  push:
    branches: [ main, actions_test ]

name: Quarto publish to another Github repository

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Clone Website repository
        shell: bash
        env:
          ACCESS_TOKEN: ${{ secrets.TRICKYTANK_REPO_ACCESS_TOKEN }}
        run: |
          git clone https://trickytank:${ACCESS_TOKEN}@github.com/trickytank/test-linkdatagen-manual.git

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Install TinyTex
        run: |
          quarto install tool tinytex

      - name: Render Quarto Project
        uses: quarto-dev/quarto-actions/render@v2

      - name: git add, commit and push
        shell: bash
        env:
          ACCESS_TOKEN: ${{ secrets.TRICKYTANK_REPO_ACCESS_TOKEN }}
        run: |
          LDG_SITE=test-linkdatagen-manual/path/to/ldg
          mkdir -p "$LDG_SITE"
          rm -fr "$LDG_SITE"/*
          cp -R _book/* "$LDG_SITE/"
          cd "$LDG_SITE"
          git add *
          git commit -m "linkdatagen - ${GITHUB_SHA}"
          git push https://trickytank:${ACCESS_TOKEN}@github.com/trickytank/test-linkdatagen-manual.git
